version: '3'

services:
  challenge:
    image: postgres:14-alpine
    ports:
      - 3339:5432
    container_name: challenge-MKS
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc.123
      POSTGRES_DB: movie